import Aside from "@/components/Aside";
import Header from "@/components/Header";
import TableOfContents from "@/components/TableOfContents";
import { generateSidebar } from '@/utils/generateSidebar';
import { generateToc } from "@/utils/getToc";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sidebarSections = await generateSidebar()
  const toc = await generateToc();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-background antialiased`}
      >
        <div className="relative flex min-h-screen flex-col bg-background">
          <div className="border-border/40 dark:border-border">
            <div className="mx-auto w-full border-border/40 dark:border-border min-[1800px]:max-w-[1536px] min-[1800px]:border-x">
              <Header />
              <div className="flex-1">
                <div className="container flex-1 items-start md:grid md:grid-cols-[220px_minmax(0,1fr)] md:gap-6 lg:grid-cols-[240px_minmax(0,1fr)] lg:gap-10 mx-auto">
                  <Aside sections={sidebarSections} />
                  <main className="relative py-6 lg:gap-10 lg:py-8 xl:grid xl:grid-cols-[1fr_300px]">
                    <div className="mx-auto w-full min-w-0 max-w-3xl">
                      {children}
                    </div>
                    <TableOfContents records={toc} />
                  </main>
                </div>
              </div>
              <footer className="border-t border-border/40 py-6 dark:border-border md:px-8 md:py-0">
                <div className="container flex flex-col items-center justify-between gap-4 md:h-24 md:flex-row">
                  <p className="text-balance text-center text-sm leading-loose text-muted-foreground md:text-left">Built by
                    <a href="https://twitter.com/shadcn" target="_blank" rel="noreferrer" className="font-medium underline underline-offset-4">shadcn</a>.
                    The source code is available on <a href="https://github.com/shadcn-ui/ui" target="_blank" rel="noreferrer" className="font-medium underline underline-offset-4">GitHub</a>.
                  </p>
                </div>
              </footer>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
